/**
 * RLS policy integration tests.
 * Runs against a real local Supabase instance (supabase start).
 * Never mocked — a mock cannot prove RLS policies work.
 *
 * Pattern per test:
 *   1. Insert test data as service role (bypasses RLS)
 *   2. Query as the target role's JWT
 *   3. Assert which rows are returned / blocked
 */

import { createClient, SupabaseClient } from '@supabase/supabase-js'
import { describe, it, expect, beforeAll, afterAll } from 'vitest'
import ws from 'ws'

// Local Supabase dev defaults — these are the standard keys generated by `supabase start`
// and are not real secrets. Safe to hardcode here for test convenience.
const SUPABASE_URL = 'http://127.0.0.1:54321'
const SERVICE_KEY  = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU'
const ANON_KEY     = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0'

// ws satisfies Node's WebSocket API but its constructor signature diverges from
// Supabase's WebSocketLikeConstructor — cast required for Node test environments.
const clientOptions = { realtime: { transport: ws as unknown as typeof WebSocket } }

// Service role client — bypasses RLS. Used for setup and teardown only.
const serviceClient = createClient(SUPABASE_URL, SERVICE_KEY, clientOptions)

// Helper: sign in a test user and return an authed client scoped to that user's JWT.
async function clientAs(email: string, password: string): Promise<SupabaseClient> {
  const client = createClient(SUPABASE_URL, ANON_KEY, clientOptions)
  const { error } = await client.auth.signInWithPassword({ email, password })
  if (error) throw new Error(`signIn failed for ${email}: ${error.message}`)
  return client
}

// ─── Fixtures ────────────────────────────────────────────────────────────────

const PASSWORDS = { admin: 'password123', rsm_north: 'password123', rsm_south: 'password123', sector_mgr: 'password123' }

let regionNorthId: string
let regionSouthId: string
let sectorId: string
let stageId: string
let createdStageId: string | null = null
let adminUserId: string
let rsmNorthUserId: string
let rsmSouthUserId: string
let sectorMgrUserId: string
let opportunityNorthId: string
let opportunitySouthId: string
let clientNorthId: string
let clientSouthId: string
let contractNorthId: string

async function createAuthUser(email: string, password: string): Promise<string> {
  const { data, error } = await serviceClient.auth.admin.createUser({
    email,
    password,
    email_confirm: true,
  })
  if (error) throw new Error(`createUser ${email}: ${error.message}`)
  return data.user.id
}

beforeAll(async () => {
  // Regions
  const { data: regions, error: regionsError } = await serviceClient.from('regions').insert([
    { name: 'RLS_Test_North' },
    { name: 'RLS_Test_South' },
  ]).select('id, name')
  if (regionsError) throw new Error(`insert regions: ${regionsError.message}`)
  regionNorthId = regions!.find(r => r.name === 'RLS_Test_North')!.id
  regionSouthId = regions!.find(r => r.name === 'RLS_Test_South')!.id

  // Sector
  const { data: sectors } = await serviceClient.from('sectors').insert([{ name: 'RLS_Test_Sector' }]).select('id')
  sectorId = sectors![0].id

  // Stage
  const { data: stages } = await serviceClient.from('pipeline_stages')
    .select('id').eq('name', 'New').limit(1)
  stageId = stages![0]?.id
  if (!stageId) {
    const { data: newStage } = await serviceClient.from('pipeline_stages')
      .insert({ name: 'RLS_Test_Stage', display_order: 99 }).select('id')
    stageId = newStage![0].id
    createdStageId = stageId
  }

  // Auth users
  const adminEmail    = 'rls.admin@test.local'
  const rsmNorthEmail = 'rls.rsm.north@test.local'
  const rsmSouthEmail = 'rls.rsm.south@test.local'
  const sectorEmail   = 'rls.sector@test.local'

  adminUserId    = await createAuthUser(adminEmail,    PASSWORDS.admin)
  rsmNorthUserId = await createAuthUser(rsmNorthEmail, PASSWORDS.rsm_north)
  rsmSouthUserId = await createAuthUser(rsmSouthEmail, PASSWORDS.rsm_south)
  sectorMgrUserId = await createAuthUser(sectorEmail,  PASSWORDS.sector_mgr)

  // CRM user rows
  await serviceClient.from('users').insert([
    { id: adminUserId,    email: adminEmail,    full_name: 'RLS Admin',      role: 'admin' },
    { id: rsmNorthUserId, email: rsmNorthEmail, full_name: 'RLS RSM North',  role: 'rsm',            region_id: regionNorthId },
    { id: rsmSouthUserId, email: rsmSouthEmail, full_name: 'RLS RSM South',  role: 'rsm',            region_id: regionSouthId },
    { id: sectorMgrUserId,email: sectorEmail,   full_name: 'RLS Sector Mgr', role: 'sector_manager' },
  ])

  // Assign sectorMgr to sector
  await serviceClient.from('user_sectors').insert({ user_id: sectorMgrUserId, sector_id: sectorId })

  // Clients
  const { data: clientsData } = await serviceClient.from('clients').insert([
    { name: 'RLS Client North', country: 'Norway', region_id: regionNorthId },
    { name: 'RLS Client South', country: 'Brazil', region_id: regionSouthId },
  ]).select('id, name')
  clientNorthId = clientsData!.find(c => c.name === 'RLS Client North')!.id
  clientSouthId = clientsData!.find(c => c.name === 'RLS Client South')!.id

  // Opportunities
  const oppBase = {
    stage_id: stageId,
    sector_id: sectorId,
    requirement_type: 'RLS Test',
    description: 'RLS test opportunity',
    prospect_company_name: 'RLS Test Co',
    country: 'Norway',
    lead_source: 'inbound' as const,
    registration_date: '2025-01-01',
  }
  const { data: opps } = await serviceClient.from('opportunities').insert([
    { ...oppBase, rsm_id: rsmNorthUserId, region_id: regionNorthId, prospect_company_name: 'RLS North Co' },
    { ...oppBase, rsm_id: rsmSouthUserId, region_id: regionSouthId, prospect_company_name: 'RLS South Co' },
  ]).select('id, prospect_company_name')
  opportunityNorthId = opps!.find(o => o.prospect_company_name === 'RLS North Co')!.id
  opportunitySouthId = opps!.find(o => o.prospect_company_name === 'RLS South Co')!.id

  // Contract for North opportunity
  const { data: contracts } = await serviceClient.from('contracts').insert([{
    opportunity_id: opportunityNorthId,
    client_id: clientNorthId,
    contract_value: 100000,
    currency: 'USD',
    signed_date: '2025-03-01',
    expected_delivery_date: '2026-01-01',
  }]).select('id')
  contractNorthId = contracts![0].id
}, 30000)

afterAll(async () => {
  // Clean up in reverse FK order
  await serviceClient.from('contracts').delete().eq('id', contractNorthId)
  await serviceClient.from('opportunities').delete().in('id', [opportunityNorthId, opportunitySouthId])
  await serviceClient.from('clients').delete().in('id', [clientNorthId, clientSouthId])
  await serviceClient.from('user_sectors').delete().eq('user_id', sectorMgrUserId)
  await serviceClient.from('users').delete().in('id', [adminUserId, rsmNorthUserId, rsmSouthUserId, sectorMgrUserId])
  await serviceClient.from('regions').delete().in('id', [regionNorthId, regionSouthId])
  await serviceClient.from('sectors').delete().eq('id', sectorId)
  if (createdStageId) {
    await serviceClient.from('pipeline_stages').delete().eq('id', createdStageId)
  }
  await serviceClient.auth.admin.deleteUser(adminUserId)
  await serviceClient.auth.admin.deleteUser(rsmNorthUserId)
  await serviceClient.auth.admin.deleteUser(rsmSouthUserId)
  await serviceClient.auth.admin.deleteUser(sectorMgrUserId)
}, 15000)

// ─── Opportunities ────────────────────────────────────────────────────────────

describe('opportunities RLS', () => {
  it('admin sees all opportunities', async () => {
    const admin = await clientAs('rls.admin@test.local', PASSWORDS.admin)
    const { data, error } = await admin.from('opportunities')
      .select('id').in('id', [opportunityNorthId, opportunitySouthId])
    expect(error).toBeNull()
    expect(data).toHaveLength(2)
  })

  it('rsm sees only own region opportunities', async () => {
    const rsm = await clientAs('rls.rsm.north@test.local', PASSWORDS.rsm_north)
    const { data, error } = await rsm.from('opportunities')
      .select('id').in('id', [opportunityNorthId, opportunitySouthId])
    expect(error).toBeNull()
    expect(data).toHaveLength(1)
    expect(data![0].id).toBe(opportunityNorthId)
  })

  it('rsm cannot see other region opportunities', async () => {
    const rsm = await clientAs('rls.rsm.north@test.local', PASSWORDS.rsm_north)
    const { data } = await rsm.from('opportunities')
      .select('id').eq('id', opportunitySouthId)
    expect(data).toHaveLength(0)
  })

  it('sector_manager (scope=all) sees all opportunities', async () => {
    const sm = await clientAs('rls.sector@test.local', PASSWORDS.sector_mgr)
    const { data, error } = await sm.from('opportunities')
      .select('id').in('id', [opportunityNorthId, opportunitySouthId])
    expect(error).toBeNull()
    expect(data).toHaveLength(2)
  })

  it('sector_manager (scope=own_sectors_only) sees only assigned sectors', async () => {
    // Set sector_scope to own_sectors_only
    await serviceClient.from('users').update({ sector_scope: 'own_sectors_only' }).eq('id', sectorMgrUserId)

    const sm = await clientAs('rls.sector@test.local', PASSWORDS.sector_mgr)
    // Both test opportunities use the RLS_Test_Sector which is assigned to this SM
    const { data } = await sm.from('opportunities')
      .select('id').in('id', [opportunityNorthId, opportunitySouthId])
    expect(data).toHaveLength(2)

    // Reset
    await serviceClient.from('users').update({ sector_scope: 'all' }).eq('id', sectorMgrUserId)
  })

  it('rsm cannot insert opportunity in another region', async () => {
    const rsm = await clientAs('rls.rsm.north@test.local', PASSWORDS.rsm_north)
    const { error } = await rsm.from('opportunities').insert({
      rsm_id: rsmNorthUserId,
      region_id: regionSouthId, // wrong region
      stage_id: stageId,
      sector_id: sectorId,
      requirement_type: 'Test',
      description: 'Test',
      prospect_company_name: 'Test Co',
      country: 'Brazil',
      lead_source: 'inbound',
      registration_date: '2025-01-01',
    })
    expect(error).not.toBeNull()
  })
})

// ─── Clients ─────────────────────────────────────────────────────────────────

describe('clients RLS', () => {
  it('admin sees all clients', async () => {
    const admin = await clientAs('rls.admin@test.local', PASSWORDS.admin)
    const { data, error } = await admin.from('clients')
      .select('id').in('id', [clientNorthId, clientSouthId])
    expect(error).toBeNull()
    expect(data).toHaveLength(2)
  })

  it('rsm sees only own region clients', async () => {
    const rsm = await clientAs('rls.rsm.north@test.local', PASSWORDS.rsm_north)
    const { data, error } = await rsm.from('clients')
      .select('id').in('id', [clientNorthId, clientSouthId])
    expect(error).toBeNull()
    expect(data).toHaveLength(1)
    expect(data![0].id).toBe(clientNorthId)
  })

  it('sector_manager sees all clients', async () => {
    const sm = await clientAs('rls.sector@test.local', PASSWORDS.sector_mgr)
    const { data, error } = await sm.from('clients')
      .select('id').in('id', [clientNorthId, clientSouthId])
    expect(error).toBeNull()
    expect(data).toHaveLength(2)
  })

  it('rsm cannot delete a client', async () => {
    const rsm = await clientAs('rls.rsm.north@test.local', PASSWORDS.rsm_north)
    await rsm.from('clients').delete().eq('id', clientNorthId)
    // PostgREST returns no error when RLS blocks a DELETE — it just deletes 0 rows.
    // Verify the row still exists to confirm the delete was blocked.
    const { data } = await serviceClient.from('clients').select('id').eq('id', clientNorthId)
    expect(data).toHaveLength(1)
  })
})

// ─── Contracts ────────────────────────────────────────────────────────────────

describe('contracts RLS', () => {
  it('admin sees all contracts', async () => {
    const admin = await clientAs('rls.admin@test.local', PASSWORDS.admin)
    const { data, error } = await admin.from('contracts').select('id').eq('id', contractNorthId)
    expect(error).toBeNull()
    expect(data).toHaveLength(1)
  })

  it('rsm sees contracts for own opportunities', async () => {
    const rsm = await clientAs('rls.rsm.north@test.local', PASSWORDS.rsm_north)
    const { data, error } = await rsm.from('contracts').select('id').eq('id', contractNorthId)
    expect(error).toBeNull()
    expect(data).toHaveLength(1)
  })

  it('rsm cannot update contract terms', async () => {
    const rsm = await clientAs('rls.rsm.north@test.local', PASSWORDS.rsm_north)
    const { error } = await rsm.from('contracts')
      .update({ contract_value: 999999 })
      .eq('id', contractNorthId)
    expect(error).not.toBeNull()
  })

  it('rsm can toggle is_at_risk on own contract', async () => {
    const rsm = await clientAs('rls.rsm.north@test.local', PASSWORDS.rsm_north)
    const { error } = await rsm.from('contracts')
      .update({ is_at_risk: true })
      .eq('id', contractNorthId)
    expect(error).toBeNull()
    const { data } = await serviceClient.from('contracts').select('is_at_risk').eq('id', contractNorthId)
    expect(data![0].is_at_risk).toBe(true)
    // Reset
    await serviceClient.from('contracts').update({ is_at_risk: false }).eq('id', contractNorthId)
  })

  it('sector_manager sees all contracts', async () => {
    const sm = await clientAs('rls.sector@test.local', PASSWORDS.sector_mgr)
    const { data, error } = await sm.from('contracts').select('id').eq('id', contractNorthId)
    expect(error).toBeNull()
    expect(data).toHaveLength(1)
  })

  it('sector_manager cannot write contracts', async () => {
    const sm = await clientAs('rls.sector@test.local', PASSWORDS.sector_mgr)
    await sm.from('contracts').update({ is_at_risk: true }).eq('id', contractNorthId)
    // PostgREST returns no error when RLS blocks an UPDATE — verify the value did not change.
    const { data } = await serviceClient.from('contracts').select('is_at_risk').eq('id', contractNorthId)
    expect(data![0].is_at_risk).toBe(false)
  })
})

// ─── Lookup tables ────────────────────────────────────────────────────────────

describe('lookup table RLS', () => {
  it('all roles can read pipeline_stages', async () => {
    const rsm = await clientAs('rls.rsm.north@test.local', PASSWORDS.rsm_north)
    const { data, error } = await rsm.from('pipeline_stages').select('id')
    expect(error).toBeNull()
    expect(data!.length).toBeGreaterThan(0)
  })

  it('rsm cannot write pipeline_stages', async () => {
    const rsm = await clientAs('rls.rsm.north@test.local', PASSWORDS.rsm_north)
    const { error } = await rsm.from('pipeline_stages')
      .insert({ name: 'Rogue Stage', display_order: 99 })
    expect(error).not.toBeNull()
  })

  it('admin can write pipeline_stages', async () => {
    const admin = await clientAs('rls.admin@test.local', PASSWORDS.admin)
    const { data, error } = await admin.from('pipeline_stages')
      .insert({ name: 'RLS_Test_Stage_Admin', display_order: 98 })
      .select('id')
    expect(error).toBeNull()
    // Clean up
    await serviceClient.from('pipeline_stages').delete().eq('id', data![0].id)
  })
})

// ─── Deactivated users ────────────────────────────────────────────────────────

describe('deactivated user RLS', () => {
  it('auth_role() returns null for a deactivated user, blocking every role-gated policy', async () => {
    await serviceClient.from('users').update({ is_active: false }).eq('id', rsmNorthUserId)
    try {
      const rsm = await clientAs('rls.rsm.north@test.local', PASSWORDS.rsm_north)
      const { data, error } = await rsm.from('opportunities')
        .select('id').eq('id', opportunityNorthId)
      expect(error).toBeNull()
      expect(data).toHaveLength(0)
    } finally {
      await serviceClient.from('users').update({ is_active: true }).eq('id', rsmNorthUserId)
    }
  })

  it('a deactivated user can still read their own users row (unaffected by auth_role)', async () => {
    await serviceClient.from('users').update({ is_active: false }).eq('id', rsmNorthUserId)
    try {
      const rsm = await clientAs('rls.rsm.north@test.local', PASSWORDS.rsm_north)
      const { data, error } = await rsm.from('users').select('id, is_active').eq('id', rsmNorthUserId)
      expect(error).toBeNull()
      expect(data).toHaveLength(1)
      expect(data![0].is_active).toBe(false)
    } finally {
      await serviceClient.from('users').update({ is_active: true }).eq('id', rsmNorthUserId)
    }
  })
})
